// ─── CDN base for official AWS Architecture Icons ───
const CDN = "https://cdn.jsdelivr.net/npm/aws-icons@latest/icons";

export const ICON_MAP = {
  route53: `${CDN}/architecture-service/AmazonRoute53.svg`,
  cloudfront: `${CDN}/architecture-service/AmazonCloudFront.svg`,
  waf: `${CDN}/architecture-service/AWSWAF.svg`,
  shield: `${CDN}/architecture-service/AWSShield.svg`,
  acm: `${CDN}/architecture-service/AWSCertificateManager.svg`,
  s3: `${CDN}/architecture-service/AmazonSimpleStorageService.svg`,
  vpc: `${CDN}/architecture-service/AmazonVirtualPrivateCloud.svg`,
  alb: `${CDN}/architecture-service/ElasticLoadBalancing.svg`,
  ecs: `${CDN}/architecture-service/AmazonElasticContainerService.svg`,
  fargate: `${CDN}/architecture-service/AWSFargate.svg`,
  dynamodb: `${CDN}/architecture-service/AmazonDynamoDB.svg`,
  dynamodbStreams: `${CDN}/architecture-service/AmazonDynamoDB.svg`,
  sqs: `${CDN}/architecture-service/AmazonSimpleQueueService.svg`,
  eventbridge: `${CDN}/architecture-service/AmazonEventBridge.svg`,
  lambda: `${CDN}/architecture-service/AWSLambda.svg`,
  secrets: `${CDN}/architecture-service/AWSSecretsManager.svg`,
  kms: `${CDN}/architecture-service/AWSKeyManagementService.svg`,
  cognito: `${CDN}/architecture-service/AmazonCognito.svg`,
  cloudwatch: `${CDN}/architecture-service/AmazonCloudWatch.svg`,
  xray: `${CDN}/architecture-service/AWSXRay.svg`,
  cloudtrail: `${CDN}/architecture-service/AWSCloudTrail.svg`,
  guardduty: `${CDN}/architecture-service/AmazonGuardDuty.svg`,
  ecr: `${CDN}/architecture-service/AmazonElasticContainerRegistry.svg`,
  codepipeline: `${CDN}/architecture-service/AWSCodePipeline.svg`,
  elasticache: `${CDN}/architecture-service/AmazonElastiCache.svg`,
  endpoint: `${CDN}/resource/AmazonVPCEndpoints.svg`,
  natgw: `/aws-icons/nat-gateway.svg`,
  igw: `/aws-icons/internet-gateway.svg`,
  sg: `${CDN}/resource/SecurityGroup.svg`,
};

export const ARCHITECTURE = {
  title: "AAA Production Ecommerce Tier 3 - Multi-AZ AWS Architecture",
  description: "React on S3/CloudFront · ECS Fargate Node.js microservices · DynamoDB · async events · multi-AZ VPC",
  explanation: {
    title: "my-ecommerce.com - Production AWS Ecommerce Architecture",
    intro: "This page explains the production architecture behind the fake domain my-ecommerce.com. It is written to help someone learning AWS understand what each layer does, which technologies are used, and why those decisions make sense in a real ecommerce system.",
    sections: [
      {
        id: "general",
        title: "General Description",
        explanation: "my-ecommerce.com is a production-grade ecommerce platform designed for high availability, security, scalability, and maintainability. It uses AWS managed services, containerized backend services, serverless async processing, and a static React frontend.",
      },
      {
        id: "edge-dns",
        title: "Edge and DNS Layer",
        technologies: ["Route 53", "CloudFront", "AWS WAF", "ACM"],
        explanation: "Users access my-ecommerce.com through Route 53. CloudFront improves performance by caching static content globally. AWS WAF protects against common web attacks. ACM provides TLS certificates for HTTPS.",
        decision: "This layer improves security, global performance, and controlled public access.",
      },
      {
        id: "frontend",
        title: "Frontend Layer",
        technologies: ["React SPA", "S3", "CloudFront"],
        explanation: "The frontend is a React single-page application hosted in S3 and served through CloudFront.",
        decision: "This keeps the frontend simple, cheap, highly available, and easy to deploy.",
      },
      {
        id: "network",
        title: "Network Layer",
        technologies: ["VPC", "Multi-AZ subnets", "Public subnets", "Private subnets", "Internet Gateway", "NAT Gateway", "Security Groups"],
        explanation: "The architecture uses a VPC across multiple Availability Zones. Public subnets host the ALB and NAT Gateways. Backend services run in private subnets.",
        decision: "This isolates backend services from the public internet while keeping the system highly available.",
      },
      {
        id: "api-backend",
        title: "API and Backend Layer",
        technologies: ["Application Load Balancer", "ECS Fargate", "Docker", "Node.js / Express"],
        services: ["User Profile Service", "Catalog Service", "Cart Service", "Order Service"],
        explanation: "The ALB is the main Layer 7 gateway inside the VPC. It uses host and path-based listener rules to route `/api/users/*`, `/api/catalog/*`, `/api/cart/*`, and `/api/orders/*` toward separate ECS target groups running on Fargate.",
        decision: "An ALB is enough here because the system needs HTTPS termination and path-based routing to ECS services, not full API management features such as request transformation, usage plans, or Cognito authorizers at the gateway.",
      },
      {
        id: "auth",
        title: "Authentication Layer",
        technologies: ["Amazon Cognito"],
        explanation: "Amazon Cognito handles sign-up, sign-in, token issuance, refresh tokens, and user identity. The backend services trust Cognito as the identity provider and validate Cognito-issued JWTs instead of implementing a custom authentication service.",
        decision: "Using Cognito removes the need for a bespoke auth service in this architecture and sharply reduces security and operational complexity.",
      },
      {
        id: "async",
        title: "Async Processing Layer",
        technologies: ["Amazon SQS", "Dead-letter Queue", "Lambda Consumer", "EventBridge"],
        explanation: "The Order Service writes a durable order record and enqueues a checkout job onto SQS. A dedicated consumer processes the message, calls the payment flow, retries safely on transient failures, and redrives poison messages to a DLQ after the maximum receive count.",
        decision: "SQS decouples checkout from slower downstream work, smooths traffic spikes, and gives the system explicit retry and failure-isolation mechanics.",
      },
      {
        id: "payment",
        title: "Payment Layer",
        technologies: ["Payment Service", "Secrets Manager", "External payment provider", "Webhooks"],
        explanation: "The Payment Service handles payment requests, communicates with an external payment provider, and processes webhook callbacks.",
        decision: "Payment logic is isolated because it is sensitive, failure-prone, and requires idempotency.",
      },
      {
        id: "data",
        title: "Data Layer",
        technologies: ["DynamoDB", "S3"],
        services: ["Orders table", "Payments table", "S3 invoices/assets bucket"],
        explanation: "DynamoDB stores order and payment records. S3 stores invoices, receipts, and static assets.",
        decision: "DynamoDB provides scalable managed NoSQL storage, while S3 is reliable and cost-effective for files.",
      },
      {
        id: "security",
        title: "Security Layer",
        technologies: ["IAM roles", "Secrets Manager", "KMS", "Security Groups", "WAF"],
        explanation: "Each service uses least-privilege IAM roles. Secrets are stored in Secrets Manager. Data encryption uses KMS. Security Groups restrict network traffic.",
        decision: "Security is applied at identity, network, application, and data layers.",
      },
      {
        id: "observability",
        title: "Observability Layer",
        technologies: ["CloudWatch Logs", "CloudWatch Metrics", "CloudWatch Alarms", "Optional X-Ray"],
        explanation: "Logs, metrics, and alarms are collected to monitor service health, errors, latency, and failed async jobs.",
        decision: "Observability helps detect failures quickly and supports production troubleshooting.",
      },
      {
        id: "cicd",
        title: "CI/CD Layer",
        technologies: ["GitHub Actions or CodePipeline", "ECR", "ECS Deployments", "S3 deploy for frontend"],
        explanation: "Frontend builds are uploaded to S3. Backend containers are built, pushed to ECR, and deployed to ECS Fargate.",
        decision: "This enables repeatable, automated, and safer production deployments.",
      },
    ],
    summary: "This architecture is a strong fit for a Tier 3 ecommerce application because it is multi-AZ, secure by default, scalable, simple enough to maintain, and production-ready without unnecessary overengineering.",
  },
  defaultSpread: 1.4,
  defaultLayer: "frontend",
  flowGuides: {
    frontend: [
      {
        step: 1,
        title: "The browser looks up the storefront domain",
        explanation: "A customer opens the ecommerce site, and the browser first performs a DNS lookup. Route 53 answers for the custom domain and directs the request toward the CloudFront distribution.",
        color: "#2563EB",
      },
      {
        step: 2,
        title: "Route 53 resolves traffic to CloudFront",
        explanation: "Route 53 maps the domain to CloudFront so the user reaches the nearest edge location. This gives the storefront low-latency delivery and a globally consistent entry point.",
        color: "#2563EB",
      },
      {
        step: 3,
        title: "CloudFront applies edge protection with WAF",
        explanation: "Before serving content, the request is inspected through the WAF policy attached to the CloudFront path. This helps block malicious requests and enforce edge security for the frontend.",
        color: "#2563EB",
      },
      {
        step: 5,
        title: "CloudFront serves the React app from S3",
        explanation: "For frontend assets such as HTML, JavaScript, and CSS, CloudFront fetches from the S3 origin and caches the result. The React application is then delivered back to the browser over HTTPS.",
        color: "#2563EB",
      },
    ],
    backend: [
      {
        step: 1,
        title: "The browser starts with DNS resolution",
        explanation: "The backend request path still begins with the customer browser resolving the ecommerce domain. Route 53 is the authoritative DNS service that points the request to CloudFront.",
        color: "#ED7100",
      },
      {
        step: 2,
        title: "Route 53 sends the request to CloudFront",
        explanation: "Route 53 hands traffic to CloudFront so all API calls share the same public entry point as the storefront. This keeps the user experience consistent and allows edge controls to be centralized.",
        color: "#ED7100",
      },
      {
        step: 3,
        title: "WAF screens the incoming request",
        explanation: "CloudFront forwards the API request through the WAF protections before it reaches regional infrastructure. This is where application-layer filtering and request inspection happen.",
        color: "#ED7100",
      },
      {
        step: 4,
        title: "Approved API traffic is sent to the ALB",
        explanation: "If the request matches an API path such as `/api/*`, CloudFront forwards it toward the regional backend entry point after WAF inspection. The Application Load Balancer is the public application gateway inside the VPC.",
        color: "#ED7100",
      },
      {
        step: 5,
        title: "Cognito issues the JWT used by the backend",
        explanation: "The customer authenticates with Amazon Cognito and receives a JWT. That token is attached to API requests and trusted by the backend services as the source of identity.",
        color: "#ED7100",
      },
      {
        step: 6,
        title: "The ALB path-routes the request to the correct ECS service",
        explanation: "The ALB applies listener rules and forwards the request only to the matching ECS target group. For checkout, `/api/orders/*` goes to the Order Service; the ALB does not broadcast a request to every ECS service.",
        color: "#ED7100",
      },
      {
        step: 7,
        title: "The Order Service creates the order and enqueues a checkout job",
        explanation: "The Order Service validates the Cognito token, persists the pending order, and places a checkout command on SQS so the API can respond without waiting for downstream payment and notification work.",
        color: "#ED7100",
      },
      {
        step: 8,
        title: "The SQS consumer processes the checkout message",
        explanation: "A dedicated worker consumes the SQS message, performs retry-safe checkout processing, and invokes the Payment Service only from the asynchronous path.",
        color: "#ED7100",
      },
      {
        step: 9,
        title: "The Payment Service reaches the provider through NAT egress",
        explanation: "The Payment Service retrieves provider credentials from Secrets Manager and calls the external processor over HTTPS. NAT Gateway A or B is only the zonal outbound path for private tasks; it is not a business-level service hop.",
        color: "#ED7100",
      },
      {
        step: 10,
        title: "Failures are retried and then redriven to the DLQ",
        explanation: "If processing keeps failing, the SQS redrive policy moves the message to the dead-letter queue for inspection and replay instead of blocking the rest of the workload.",
        color: "#ED7100",
      },
    ],
  },
  layerViews: [
    { id: "frontend", label: "Frontend", color: "#2563EB" },
    { id: "backend", label: "Backend", color: "#ED7100" },
    { id: "storage", label: "Storage", color: "#7C3AED" },
    { id: "security", label: "Security", color: "#DD344C" },
    { id: "observability", label: "Observability", color: "#D97706" },
    { id: "devops", label: "DevOps", color: "#0F766E" },
  ],
  boundaries: [
    {
      id: "aws",
      label: "AWS Cloud",
      color: "#232F3E",
      x: 30, y: 15, w: 1390, h: 780,
      style: "solid",
      layers: ["frontend", "backend", "storage", "security", "observability", "devops"],
    },
    {
      id: "region",
      label: "Region (us-east-1)",
      color: "#147EBA",
      x: 55, y: 45, w: 1340, h: 735,
      style: "solid",
      layers: ["frontend", "backend", "storage", "security", "observability", "devops"],
      detail: "This production ecommerce platform is deployed in a single AWS Region and distributed across multiple Availability Zones for high availability. Regional services such as CloudFront integrations, Cognito, DynamoDB, EventBridge, and CI/CD coordinate with the VPC-hosted application tier to provide a resilient AAA production setup.",
    },
    {
      id: "edge-layer",
      label: "Edge / DNS / Frontend",
      color: "#2563EB",
      x: 70, y: 70, w: 200, h: 570,
      style: "dashed",
      group: "frontend",
      layers: ["frontend", "backend", "security"],
      detail: "This layer terminates user traffic at the edge, handles DNS, CDN caching, DDoS protection, TLS, and serves the React single-page application from Amazon S3 through CloudFront.",
    },
    {
      id: "vpc",
      label: "VPC (10.0.0.0/16)",
      color: "#8C4FFF",
      x: 270, y: 150, w: 770, h: 600,
      style: "solid",
      group: "networking",
      iconType: "aws",
      awsIcon: "vpc",
      layers: ["backend", "storage", "observability", "devops"],
      detail: "The VPC is the main private network boundary for the ecommerce workload. It spans multiple Availability Zones and separates internet-facing ingress in public subnets from application workloads in private subnets while using NAT gateways and VPC endpoints for controlled outbound and private service access.",
    },
    {
      id: "az-a",
      label: "Availability Zone A",
      color: "#0F766E",
      x: 300, y: 185, w: 345, h: 525,
      style: "dashed",
      group: "networking",
      layers: ["backend", "storage", "observability", "devops"],
      detail: "AZ A contains one public subnet and one private application subnet. Running the same ingress and service topology in each Availability Zone allows the platform to keep serving traffic even if one zone degrades.",
    },
    {
      id: "az-b",
      label: "Availability Zone B",
      color: "#0F766E",
      x: 665, y: 185, w: 345, h: 525,
      style: "dashed",
      group: "networking",
      layers: ["backend", "storage", "observability", "devops"],
      detail: "AZ B mirrors the subnet structure and compute placement of AZ A. This symmetric design supports ALB target distribution, Fargate task spread, and NAT resilience for production traffic.",
    },
    {
      id: "public-a",
      label: "Public Subnet A",
      color: "#1D4ED8",
      x: 320, y: 215, w: 305, h: 120,
      style: "dashed",
      group: "edge",
      layers: ["backend"],
      detail: "This public subnet hosts internet-facing ingress resources such as the Application Load Balancer nodes and a zonal NAT Gateway for private subnet egress.",
    },
    {
      id: "public-b",
      label: "Public Subnet B",
      color: "#1D4ED8",
      x: 685, y: 215, w: 305, h: 120,
      style: "dashed",
      group: "edge",
      layers: ["backend"],
      detail: "This public subnet mirrors the ingress and NAT pattern of Public Subnet A so that edge entry and egress continue to function across both Availability Zones.",
    },
    {
      id: "private-a",
      label: "Private App Subnet A",
      color: "#248814",
      x: 320, y: 360, w: 305, h: 245,
      style: "dashed",
      group: "backend",
      layers: ["backend", "storage", "observability", "devops"],
      detail: "This private application subnet hosts ECS Fargate tasks for the ecommerce microservices. Backend traffic stays private behind the ALB and reaches managed AWS services through IAM, NAT, or VPC endpoints as appropriate.",
    },
    {
      id: "private-b",
      label: "Private App Subnet B",
      color: "#248814",
      x: 685, y: 360, w: 305, h: 245,
      style: "dashed",
      group: "backend",
      layers: ["backend", "storage", "observability", "devops"],
      detail: "This private application subnet provides the second failure domain for the Fargate-backed microservices, allowing the ECS services to maintain desired task count across zones.",
    },
    {
      id: "shared-private",
      label: "Shared Private Access / Platform Services",
      color: "#7C3AED",
      x: 320, y: 620, w: 670, h: 95,
      style: "dashed",
      group: "networking",
      layers: ["storage", "security"],
      detail: "This shared private layer represents platform capabilities used by the application tier, including security groups, optional Redis cache, and private endpoints to AWS services such as DynamoDB, S3, and Secrets Manager.",
    },
    {
      id: "ecs-plane",
      label: "ECS Fargate Service Plane",
      color: "#ED7100",
      x: 345, y: 390, w: 620, h: 185,
      style: "dashed",
      group: "backend",
      iconType: "aws",
      awsIcon: "ecs",
      layers: ["backend", "storage", "observability", "devops"],
      detail: "The Node.js and Express ecommerce APIs run as ECS services on AWS Fargate. ECS spreads tasks across the private subnets in both Availability Zones and supports rolling or blue-green updates via the deployment pipeline.",
    },
    {
      id: "async-layer",
      label: "Async / Event Processing",
      color: "#D97706",
      x: 1060, y: 485, w: 300, h: 225,
      style: "dashed",
      group: "async",
      layers: ["backend", "storage", "observability"],
      detail: "Domain events, asynchronous jobs, retries, and worker execution live in this layer. It decouples synchronous checkout APIs from downstream processing such as notifications, invoice generation, and payment reconciliation.",
    },
    {
      id: "security-ops",
      label: "Security / Observability / CI-CD",
      color: "#DD344C",
      x: 1060, y: 70, w: 300, h: 170,
      style: "dashed",
      group: "security",
      layers: ["security", "observability", "devops"],
      detail: "This layer groups security services, observability, and deployment tooling that support the production platform without cluttering the main request path.",
    },
  ],
  nodes: [
    { id: "user", label: "Customer Browser", iconType: "custom", customIcon: "👤", x: 10, y: 260, group: "external", layers: ["frontend", "backend"],
      detail: "End users access the ecommerce storefront over HTTPS. Their requests resolve through Route 53, are accelerated by CloudFront, and then either fetch the React application or invoke backend APIs for authenticated commerce flows." },

    { id: "route53", label: "Amazon Route 53", iconType: "aws", awsIcon: "route53", x: 110, y: 95, group: "edge", layers: ["frontend", "backend"],
      detail: "Route 53 hosts the ecommerce DNS records and routes the storefront domain to CloudFront. It provides highly available DNS for production traffic and can be extended later with health checks and routing policies." },
    { id: "cloudfront", label: "Amazon CloudFront", iconType: "aws", awsIcon: "cloudfront", x: 110, y: 225, group: "edge", layers: ["frontend", "backend"],
      detail: "CloudFront is the global edge entry point for the ecommerce site. It serves the React app from S3, caches static content, terminates TLS with ACM certificates, and forwards API traffic toward the regional application layer." },
    { id: "waf", label: "AWS WAF", iconType: "aws", awsIcon: "waf", x: 110, y: 355, group: "security", layers: ["frontend", "backend", "security"],
      detail: "AWS WAF protects the ecommerce application from common web exploits and abusive traffic patterns. It is the application-layer protection point for both static and API traffic entering through CloudFront." },
    { id: "shield", label: "AWS Shield Std", iconType: "aws", awsIcon: "shield", x: 110, y: 485, group: "security", layers: ["security"],
      detail: "AWS Shield Standard provides baseline DDoS protection for edge services such as Route 53 and CloudFront. It helps the storefront remain reachable during volumetric attacks." },
    { id: "acm", label: "ACM Certificate", iconType: "aws", awsIcon: "acm", x: 110, y: 550, group: "security", layers: ["frontend", "security"],
      detail: "AWS Certificate Manager provides the TLS certificate used by CloudFront and can also support HTTPS termination on the Application Load Balancer." },
    { id: "web-bucket", label: "S3 React App", iconType: "aws", awsIcon: "s3", x: 110, y: 615, group: "frontend", layers: ["frontend"],
      detail: "This S3 bucket hosts the built React storefront assets. CloudFront serves these static files globally with low latency while the application code calls regional backend APIs for dynamic data." },

    { id: "igw", label: "Internet Gateway", iconType: "aws", awsIcon: "igw", x: 560, y: 105, group: "networking", layers: ["backend"],
      detail: "The Internet Gateway provides controlled internet connectivity for public subnet resources, including the internet-facing Application Load Balancer and NAT Gateways." },
    { id: "alb", label: "Application Load Balancer", iconType: "aws", awsIcon: "alb", x: 620, y: 240, group: "edge", layers: ["backend"],
      detail: "The ALB is deployed across public subnets in multiple Availability Zones. It terminates HTTPS and uses host and path-based listener rules to forward requests to the correct ECS target group. In this design it is the main backend gateway; an API Gateway is not required." },
    { id: "nat-a", label: "NAT Gateway A", iconType: "aws", awsIcon: "natgw", x: 390, y: 240, group: "networking", layers: ["backend"],
      detail: "NAT Gateway A provides outbound internet access for workloads in Private App Subnet A when those workloads must reach public AWS endpoints or third-party services. It is infrastructure-only egress, not an application-level payment hop." },
    { id: "nat-b", label: "NAT Gateway B", iconType: "aws", awsIcon: "natgw", x: 865, y: 240, group: "networking", layers: ["backend"],
      detail: "NAT Gateway B mirrors the same outbound egress role in AZ B so private workloads keep zonal resilience. Tasks in AZ B use this NAT for outbound HTTPS calls instead of crossing zones unnecessarily." },

    { id: "user-svc", label: "User Profile Svc", iconType: "aws", awsIcon: "fargate", x: 375, y: 430, group: "backend", layers: ["backend", "storage", "observability", "devops"],
      detail: "Node.js and Express service for customer profile APIs, account preferences, and application-level user data. Authentication itself is delegated to Amazon Cognito, while this service validates Cognito-issued JWTs and owns profile-oriented business endpoints." },
    { id: "catalog-svc", label: "Catalog Svc", iconType: "aws", awsIcon: "fargate", x: 500, y: 430, group: "backend", layers: ["backend", "storage", "observability", "devops"],
      detail: "Product catalog API for browsing products, pricing, categories, and inventory views. It primarily reads from DynamoDB and media assets stored in S3." },
    { id: "cart-svc", label: "Cart Svc", iconType: "aws", awsIcon: "fargate", x: 625, y: 430, group: "backend", layers: ["backend", "storage", "observability", "devops"],
      detail: "Cart service manages in-progress shopping carts, session state, promotions, and cart recalculation. Redis can be used here for hot cache or transient cart/session acceleration." },
    { id: "order-svc", label: "Order Svc", iconType: "aws", awsIcon: "fargate", x: 750, y: 430, group: "backend", layers: ["backend", "storage", "observability", "devops"],
      detail: "Order service owns checkout orchestration, order creation, and durable order writes. It emits domain events for downstream fulfillment and notification processing." },
    { id: "payment-svc", label: "Payment Svc", iconType: "aws", awsIcon: "fargate", x: 500, y: 525, group: "backend", layers: ["backend", "storage", "observability", "devops"],
      detail: "Payment service handles secure payment initiation, provider communication, and payment status updates. Payment provider credentials are retrieved from AWS Secrets Manager and protected with KMS." },
    { id: "notify-svc", label: "Notification Svc", iconType: "aws", awsIcon: "fargate", x: 750, y: 525, group: "backend", layers: ["backend", "observability", "devops"],
      detail: "Notification service handles customer-facing email or event notifications, often triggered asynchronously after orders, payments, or account events." },

    { id: "sg", label: "Security Groups", iconType: "aws", awsIcon: "sg", x: 360, y: 640, group: "security", layers: ["security"],
      detail: "Security groups constrain communication between the ALB, ECS services, cache layer, and AWS endpoints. They are the primary network policy boundary inside the VPC." },
    { id: "vpce-ddb", label: "VPC EP DynamoDB", iconType: "aws", awsIcon: "endpoint", x: 500, y: 640, group: "networking", layers: ["storage"],
      detail: "A DynamoDB VPC endpoint enables private access from the application subnets to DynamoDB without traversing the public internet." },
    { id: "vpce-s3", label: "VPC EP S3", iconType: "aws", awsIcon: "endpoint", x: 620, y: 640, group: "networking", layers: ["storage"],
      detail: "An S3 VPC endpoint lets the application tier access buckets privately for images, invoices, and deployment-related artifact retrieval." },
    { id: "vpce-secrets", label: "VPC EP Secrets", iconType: "aws", awsIcon: "endpoint", x: 740, y: 640, group: "networking", layers: ["security", "storage"],
      detail: "A Secrets Manager VPC endpoint allows backend services to retrieve secrets privately from inside the VPC." },
    { id: "redis", label: "ElastiCache Redis", iconType: "aws", awsIcon: "elasticache", x: 860, y: 640, group: "data", layers: ["storage"],
      detail: "Redis is an optional acceleration layer for session data, frequently accessed catalog fragments, rate-limit counters, or cart-related caching." },

    { id: "cognito", label: "Amazon Cognito", iconType: "aws", awsIcon: "cognito", x: 1080, y: 255, group: "auth", layers: ["backend"],
      detail: "Amazon Cognito manages user sign-up, sign-in, token issuance, refresh tokens, and identity flows for the ecommerce site. It replaces the need for a dedicated custom auth service in this architecture, and backend services validate Cognito-issued JWTs for authenticated API access." },
    { id: "s3-media", label: "S3 Media Bucket", iconType: "aws", awsIcon: "s3", x: 1200, y: 255, group: "data", layers: ["storage"],
      detail: "This S3 bucket stores product images, invoices, and other static media that support the commerce experience beyond the main frontend bundle." },
    { id: "ddb-users", label: "Users Table", iconType: "aws", awsIcon: "dynamodb", x: 1080, y: 360, group: "data", layers: ["storage"],
      detail: "DynamoDB table for customer and account data used by the user and auth flows." },
    { id: "ddb-products", label: "Products Table", iconType: "aws", awsIcon: "dynamodb", x: 1200, y: 360, group: "data", layers: ["storage"],
      detail: "DynamoDB table storing product catalog data such as SKU records, pricing metadata, availability, and merchandising attributes." },
    { id: "ddb-cart", label: "Cart Table", iconType: "aws", awsIcon: "dynamodb", x: 1080, y: 455, group: "data", layers: ["storage"],
      detail: "DynamoDB table for durable cart state where persistence is required beyond purely cached or session-local handling." },
    { id: "ddb-orders", label: "Orders Table", iconType: "aws", awsIcon: "dynamodb", x: 1200, y: 455, group: "data", layers: ["storage"],
      detail: "DynamoDB table that stores orders, checkout lifecycle state, and fulfillment-ready order records." },
    { id: "ddb-payments", label: "Payments Table", iconType: "aws", awsIcon: "dynamodb", x: 1140, y: 545, group: "data", layers: ["storage"],
      detail: "DynamoDB table storing payment attempts, status transitions, and reconciliation metadata." },
    { id: "ddb-streams", label: "DDB Streams", iconType: "aws", awsIcon: "dynamodbStreams", x: 1260, y: 545, group: "async", layers: ["storage", "observability"],
      detail: "DynamoDB Streams capture item-level data changes that can feed asynchronous workers, downstream events, and secondary processing pipelines." },

    { id: "eventbridge", label: "EventBridge", iconType: "aws", awsIcon: "eventbridge", x: 1080, y: 575, group: "async", layers: ["backend", "observability"],
      detail: "EventBridge distributes domain events such as order-created, payment-authorized, or inventory-updated to decoupled consumers." },
    { id: "sqs", label: "Checkout Queue", iconType: "aws", awsIcon: "sqs", x: 1200, y: 575, group: "async", layers: ["backend", "observability"],
      detail: "Amazon SQS buffers checkout jobs away from the synchronous API path. It absorbs spikes, supports retry semantics, and lets checkout processing continue independently from user-facing latency." },
    { id: "dlq", label: "Dead-Letter Queue", iconType: "aws", awsIcon: "sqs", x: 1080, y: 665, group: "async", layers: ["observability"],
      detail: "The dead-letter queue receives messages that exceeded the queue's maximum receive count. It gives operations a safe place to inspect poison messages, replay fixed jobs, and avoid infinite retry loops." },
    { id: "lambda", label: "Checkout Consumer", iconType: "aws", awsIcon: "lambda", x: 1200, y: 665, group: "async", layers: ["backend", "observability"],
      detail: "This Lambda acts as the SQS consumer for checkout jobs. It performs retry-safe background orchestration, invokes the Payment Service, publishes outcome events, and keeps heavy work off the request-response path." },
    { id: "payment-provider", label: "Payment Provider", iconType: "custom", customIcon: "💳", x: 1320, y: 455, group: "external", layers: ["backend"],
      detail: "External payment processor used by the payment service for authorization, capture, refunds, and payment-status callbacks." },

    { id: "cloudwatch", label: "CloudWatch", iconType: "aws", awsIcon: "cloudwatch", x: 1075, y: 90, group: "observability", layers: ["observability"],
      detail: "CloudWatch collects logs, metrics, and alarms across the ALB, ECS services, queues, and Lambda workers. It is the primary dashboard and alerting surface for the platform." },
    { id: "xray", label: "AWS X-Ray", iconType: "aws", awsIcon: "xray", x: 1190, y: 90, group: "observability", layers: ["observability"],
      detail: "X-Ray or an OpenTelemetry-compatible tracing pipeline provides end-to-end request traces across the microservices and async workflows." },
    { id: "cloudtrail", label: "CloudTrail", iconType: "aws", awsIcon: "cloudtrail", x: 1305, y: 90, group: "security", layers: ["security"],
      detail: "CloudTrail records AWS API activity for auditing, investigations, and compliance visibility across the ecommerce environment." },
    { id: "guardduty", label: "GuardDuty", iconType: "aws", awsIcon: "guardduty", x: 1075, y: 170, group: "security", layers: ["security"],
      detail: "GuardDuty continuously analyzes AWS telemetry for suspicious behavior and potential threats affecting the production environment." },
    { id: "secrets", label: "Secrets Manager", iconType: "aws", awsIcon: "secrets", x: 1190, y: 170, group: "security", layers: ["security"],
      detail: "Secrets Manager stores sensitive data such as payment provider API keys and other service credentials that should never be embedded in code or task definitions." },
    { id: "kms", label: "AWS KMS", iconType: "aws", awsIcon: "kms", x: 1305, y: 170, group: "security", layers: ["storage", "security"],
      detail: "KMS provides encryption keys used for DynamoDB, S3, Secrets Manager, and other data-at-rest encryption requirements in the production platform." },

    { id: "codepipeline", label: "CodePipeline", iconType: "aws", awsIcon: "codepipeline", x: 50, y: 710, group: "cicd", layers: ["devops"],
      detail: "The CI/CD pipeline builds, tests, and deploys the ecommerce platform. It can support rolling or blue-green releases into the ECS services for safer production changes." },
    { id: "ecr", label: "Amazon ECR", iconType: "aws", awsIcon: "ecr", x: 170, y: 710, group: "cicd", layers: ["devops"],
      detail: "ECR stores the Docker images for the Node.js and Express microservices deployed onto ECS Fargate." },
    { id: "iam", label: "IAM Roles", iconType: "custom", customIcon: "🔐", x: 290, y: 710, group: "security", layers: ["security"],
      detail: "IAM roles are assigned per service and worker so each component has the least-privileged access it needs to queues, tables, buckets, secrets, and tracing endpoints." },
  ],
  flows: [
    { from: "user", to: "route53", label: "1. DNS Query", step: 1, layers: ["frontend", "backend"] },
    { from: "route53", to: "cloudfront", label: "2. Resolve App", step: 2, layers: ["frontend", "backend"] },
    { from: "cloudfront", to: "waf", label: "3. Edge Protection", step: 3, layers: ["frontend", "backend"] },
    { from: "waf", to: "alb", label: "4. /api/* to ALB", step: 4, layers: ["backend"] },
    { from: "cloudfront", to: "web-bucket", label: "5. React SPA", step: 5, style: "dashed", layers: ["frontend"] },
    { from: "cloudfront", to: "alb", label: "", step: 0, layers: ["backend"] },
    { from: "user", to: "cognito", label: "5. Sign-in / JWT", step: 5, style: "dashed", layers: ["backend"] },
    { from: "cognito", to: "user", label: "", step: 0, style: "dashed", layers: ["backend"] },
    { from: "alb", to: "user-svc", label: "Profile APIs", step: 0, layers: ["backend"] },
    { from: "alb", to: "catalog-svc", label: "Catalog", step: 0, layers: ["backend"] },
    { from: "alb", to: "cart-svc", label: "Cart", step: 0, layers: ["backend"] },
    { from: "alb", to: "order-svc", label: "6. Checkout", step: 6, layers: ["backend"] },
    { from: "user-svc", to: "cognito", label: "Validate JWT", step: 0, style: "dashed", layers: ["backend"] },
    { from: "order-svc", to: "cognito", label: "Validate JWT", step: 0, style: "dashed", layers: ["backend"] },

    { from: "user-svc", to: "vpce-ddb", label: "", step: 0, layers: ["storage"] },
    { from: "catalog-svc", to: "vpce-ddb", label: "", step: 0, layers: ["storage"] },
    { from: "cart-svc", to: "vpce-ddb", label: "", step: 0, layers: ["storage"] },
    { from: "order-svc", to: "vpce-ddb", label: "", step: 0, layers: ["storage"] },
    { from: "payment-svc", to: "vpce-ddb", label: "", step: 0, layers: ["storage"] },
    { from: "vpce-ddb", to: "ddb-users", label: "", step: 0, layers: ["storage"] },
    { from: "vpce-ddb", to: "ddb-products", label: "", step: 0, layers: ["storage"] },
    { from: "vpce-ddb", to: "ddb-cart", label: "", step: 0, layers: ["storage"] },
    { from: "vpce-ddb", to: "ddb-orders", label: "7. Durable Writes", step: 7, layers: ["storage"] },
    { from: "vpce-ddb", to: "ddb-payments", label: "", step: 0, layers: ["storage"] },

    { from: "catalog-svc", to: "vpce-s3", label: "", step: 0, layers: ["storage"] },
    { from: "notify-svc", to: "vpce-s3", label: "", step: 0, layers: ["storage"] },
    { from: "vpce-s3", to: "s3-media", label: "Images / Invoices", step: 0, layers: ["storage"] },
    { from: "cart-svc", to: "redis", label: "Hot Cache", step: 0, style: "dashed", layers: ["storage"] },
    { from: "payment-svc", to: "vpce-secrets", label: "", step: 0, layers: ["storage", "security"] },
    { from: "vpce-secrets", to: "secrets", label: "Provider Keys", step: 0, layers: ["storage", "security"] },

    { from: "order-svc", to: "sqs", label: "8. Enqueue Checkout", step: 8, layers: ["backend", "observability"] },
    { from: "sqs", to: "lambda", label: "9. Consume / Retry", step: 9, layers: ["backend", "observability"] },
    { from: "lambda", to: "payment-svc", label: "10. Invoke Payment", step: 10, layers: ["backend", "observability"] },
    { from: "payment-svc", to: "nat-a", label: "AZ A Egress", step: 0, style: "dashed", layers: ["backend"] },
    { from: "payment-svc", to: "nat-b", label: "AZ B Egress", step: 0, style: "dashed", layers: ["backend"] },
    { from: "nat-a", to: "igw", label: "", step: 0, style: "dashed", layers: ["backend"] },
    { from: "nat-b", to: "igw", label: "", step: 0, style: "dashed", layers: ["backend"] },
    { from: "igw", to: "payment-provider", label: "11. HTTPS Charge", step: 11, layers: ["backend"] },
    { from: "payment-svc", to: "eventbridge", label: "12. Payment Events", step: 12, layers: ["backend", "observability"] },
    { from: "eventbridge", to: "notify-svc", label: "13. Notify / Fan-out", step: 13, style: "dashed", layers: ["backend", "observability"] },
    { from: "sqs", to: "dlq", label: "14. Redrive on Failure", step: 14, style: "dashed", layers: ["observability"] },
    { from: "ddb-streams", to: "lambda", label: "Stream Triggers", step: 0, style: "dashed", layers: ["storage", "observability"] },

    { from: "shield", to: "cloudfront", label: "DDoS Protect", step: 0, style: "dashed", layers: ["security"] },
    { from: "acm", to: "cloudfront", label: "TLS", step: 0, style: "dashed", layers: ["frontend", "security"] },
    { from: "igw", to: "alb", label: "", step: 0, layers: ["backend"] },
    { from: "secrets", to: "kms", label: "Encrypt", step: 0, style: "dashed", layers: ["security", "storage"] },
    { from: "ddb-orders", to: "ddb-streams", label: "", step: 0, layers: ["storage", "observability"] },
    { from: "ddb-payments", to: "ddb-streams", label: "", step: 0, layers: ["storage", "observability"] },
    { from: "codepipeline", to: "ecr", label: "Build / Push", step: 0, layers: ["devops"] },
    { from: "ecr", to: "user-svc", label: "Rolling / Blue-Green", step: 0, style: "dashed", layers: ["devops"] },
    { from: "ecr", to: "catalog-svc", label: "", step: 0, style: "dashed", layers: ["devops"] },
    { from: "ecr", to: "cart-svc", label: "", step: 0, style: "dashed", layers: ["devops"] },
    { from: "ecr", to: "order-svc", label: "", step: 0, style: "dashed", layers: ["devops"] },
    { from: "ecr", to: "payment-svc", label: "", step: 0, style: "dashed", layers: ["devops"] },
    { from: "ecr", to: "notify-svc", label: "", step: 0, style: "dashed", layers: ["devops"] },
    { from: "user-svc", to: "cloudwatch", label: "Logs / Metrics", step: 0, style: "dashed", layers: ["observability"] },
    { from: "order-svc", to: "xray", label: "Tracing", step: 0, style: "dashed", layers: ["observability"] },
    { from: "iam", to: "user-svc", label: "", step: 0, style: "dashed", layers: ["security"] },
    { from: "iam", to: "payment-svc", label: "", step: 0, style: "dashed", layers: ["security"] },
  ],
};
