// ─── CDN base for official AWS Architecture Icons ───
const CDN = "https://cdn.jsdelivr.net/npm/aws-icons@latest/icons";

export const ICON_MAP = {
  cognito:     `${CDN}/architecture-service/AmazonCognito.svg`,
  apigw:       `${CDN}/architecture-service/AmazonAPIGateway.svg`,
  waf:         `${CDN}/architecture-service/AWSWAF.svg`,
  vpclink:     `${CDN}/resource/AmazonVPCVPNGateway.svg`,
  alb:         `${CDN}/architecture-service/ElasticLoadBalancing.svg`,
  ecs:         `${CDN}/architecture-service/AmazonElasticContainerService.svg`,
  fargate:     `${CDN}/architecture-service/AWSFargate.svg`,
  dynamodb:    `${CDN}/architecture-service/AmazonDynamoDB.svg`,
  paramstore:  `${CDN}/architecture-service/AWSSystemsManager.svg`,
  kms:         `${CDN}/architecture-service/AWSKeyManagementService.svg`,
  cloudwatch:  `${CDN}/architecture-service/AmazonCloudWatch.svg`,
  eventbridge: `${CDN}/architecture-service/AmazonEventBridge.svg`,
  lambda:      `${CDN}/architecture-service/AWSLambda.svg`,
  cloudmap:    `${CDN}/architecture-service/AWSCloudMap.svg`,
  vpc:         `${CDN}/architecture-service/AmazonVirtualPrivateCloud.svg`,
  endpoint:    `${CDN}/resource/AmazonVPCEndpoints.svg`,
};

export const ARCHITECTURE = {
  title: "Multi-Tenant Config Service — AWS Architecture",
  description: "ECS Fargate microservices · gRPC inter-service comms · DynamoDB/SSM strategy pattern · EventBridge-driven refresh",
  boundaries: [
    { id: "aws", label: "AWS Cloud", color: "#232F3E", x: 50, y: 15, w: 1360, h: 780, style: "solid" },
    { id: "region", label: "Region (us-east-1)", color: "#147EBA", x: 70, y: 45, w: 1320, h: 740, style: "solid" },
    { id: "vpc", label: "VPC  10.0.0.0/16", color: "#8C4FFF", x: 130, y: 85, w: 1080, h: 620, style: "solid" },
    { id: "private-subnets", label: "Private Subnets", color: "#248814", x: 155, y: 120, w: 1035, h: 450, style: "dashed" },
    { id: "ecs-cluster", label: "ECS Fargate Cluster", color: "#ED7100", x: 175, y: 155, w: 995, h: 395, style: "dashed" },
    { id: "order-svc", label: "Order Service (ECS Service)", color: "#3B82F6", x: 195, y: 195, w: 330, h: 330, style: "solid" },
    { id: "order-task", label: "Order Task (Fargate)", color: "#60A5FA", x: 205, y: 225, w: 310, h: 280, style: "dashed" },
    { id: "config-svc", label: "Config Service (ECS Service)", color: "#D97706", x: 560, y: 195, w: 420, h: 330, style: "solid" },
    { id: "config-task", label: "Config Task (Fargate) — Cloud Map ✓", color: "#FBBF24", x: 570, y: 225, w: 400, h: 280, style: "dashed" },
  ],
  nodes: [
    { id: "client", label: "Client / Apps", iconType: "custom", customIcon: "👤", x: 20, y: 345, group: "external",
      detail: "End-user applications consuming the Order Service REST API. Authenticate via JWT tokens from Amazon Cognito. Could be web apps, mobile apps, or backend services." },
    { id: "cognito", label: "Amazon Cognito", iconType: "aws", awsIcon: "cognito", x: 90, y: 180, group: "auth",
      detail: "User pool handling authentication. Issues JWT tokens (ID + Access) via OAuth 2.0 / OIDC. API Gateway uses a Cognito Authorizer to validate tokens on every request. Supports MFA, social IdPs, and SAML federation." },
    { id: "apigw", label: "API Gateway (REST)", iconType: "aws", awsIcon: "apigw", x: 90, y: 380, group: "auth",
      detail: "Public REST API (regional endpoint). Cognito authorizer validates JWTs. Private integration via VPC Link V2 sends traffic to the internal ALB. Throttling, usage plans, and request/response mapping configured." },
    { id: "waf", label: "AWS WAF", iconType: "aws", awsIcon: "waf", x: 90, y: 530, group: "security",
      detail: "Web Application Firewall attached to API Gateway. Rules: OWASP Top 10 managed rule group, rate-based rule (2000 req/5min), geo-match blocking, SQL injection/XSS protection, bot control." },
    { id: "vpclink", label: "VPC Link V2", iconType: "aws", awsIcon: "vpclink", x: 280, y: 95, group: "networking",
      detail: "VPC Link V2 (HTTP API type) enables private integration between API Gateway and the internal ALB. No public IP exposed. Supports TLS passthrough." },
    { id: "alb", label: "Application LB", iconType: "aws", awsIcon: "alb", x: 470, y: 95, group: "networking",
      detail: "Internal Application Load Balancer. Path-based routing: /api/orders/* → Order Service target group. Health checks on /actuator/health. TLS termination with ACM certificate." },
    { id: "rest-ctrl", label: "REST Controller", iconType: "custom", customIcon: "🔴", x: 240, y: 300, group: "order",
      detail: "Spring Boot REST controller. Endpoints: POST /orders, GET /orders/{id}, PUT /orders/{id}/status. Uses @RestController with OpenAPI docs. Injects ConfigServiceClient for tenant config lookups." },
    { id: "grpc-client", label: "gRPC Client", iconType: "custom", customIcon: "📡", x: 370, y: 380, group: "order",
      detail: "Auto-generated gRPC stub from config-service.proto. Channel target: dns:///config-service.local:5000 (resolved by Cloud Map). Features: deadline propagation, retry policy (3 attempts), round-robin LB." },
    { id: "grpc-ctrl", label: "gRPC Controller", iconType: "custom", customIcon: "📡", x: 620, y: 260, group: "config",
      detail: "gRPC server on port 5000. RPCs: GetTenantConfig(tenant_id, key), RefreshConfig(key_prefix). Registered with Cloud Map via ECS service connect. Interceptors for logging, metrics, and auth propagation." },
    { id: "strategy-factory", label: "Strategy Factory", iconType: "custom", customIcon: "🏭", x: 620, y: 390, group: "config",
      detail: "Strategy pattern (GoF). Routes config requests by key prefix: tenant_config_* → DynamoDBStrategy, param_config_* → SSMStrategy. New backends added without modifying existing code (OCP)." },
    { id: "dynamo-strategy", label: "DynamoDB Strategy", iconType: "custom", customIcon: "📊", x: 810, y: 280, group: "config",
      detail: "Implements ConfigStrategy interface. Reads from DynamoDB via Gateway Endpoint. PK: tenant_id, SK: config_key. DynamoDbEnhancedClient with @DynamoDbBean mapping. Local cache with 60s TTL." },
    { id: "ssm-strategy", label: "SSM Strategy", iconType: "custom", customIcon: "⚙️", x: 810, y: 420, group: "config",
      detail: "Implements ConfigStrategy interface. Reads from SSM Parameter Store via Interface Endpoint. Supports SecureString types. getParametersByPath for batch retrieval. Local cache with 300s TTL." },
    { id: "ep-cw", label: "Endpoint (CW)", iconType: "aws", awsIcon: "endpoint", x: 870, y: 95, group: "networking",
      detail: "VPC Interface Endpoint for CloudWatch Logs & Metrics. ENI in each private subnet. Keeps observability traffic off the internet." },
    { id: "ep-dynamo", label: "Endpoint (DDB)", iconType: "aws", awsIcon: "endpoint", x: 1000, y: 220, group: "networking",
      detail: "VPC Gateway Endpoint for DynamoDB. Free of charge. Route table entry directs DynamoDB traffic through the endpoint." },
    { id: "ep-ssm", label: "Endpoint (SSM)", iconType: "aws", awsIcon: "endpoint", x: 1000, y: 400, group: "networking",
      detail: "VPC Interface Endpoint for SSM. ENI-based. Required for Parameter Store access without NAT Gateway. Private DNS enabled." },
    { id: "dynamodb", label: "Amazon DynamoDB", iconType: "aws", awsIcon: "dynamodb", x: 1150, y: 200, group: "data",
      detail: "NoSQL table: TenantConfig. PK=tenant_id (S), SK=config_key (S). On-demand capacity. Encryption at rest with KMS CMK. Point-in-time recovery enabled. DynamoDB Streams for CDC." },
    { id: "kms", label: "AWS KMS", iconType: "aws", awsIcon: "kms", x: 1300, y: 280, group: "security",
      detail: "Customer-managed CMK (alias: config-service-key). Encrypts DynamoDB at rest and SSM SecureString parameters. Auto annual rotation. CloudTrail logging for all key usage." },
    { id: "param-store", label: "Parameter Store", iconType: "aws", awsIcon: "paramstore", x: 1150, y: 400, group: "data",
      detail: "SSM Parameter Store (Advanced tier). Hierarchical paths: /config/{env}/{service}/{key}. SecureString encrypted with KMS. Change notifications via EventBridge." },
    { id: "cloudwatch", label: "CloudWatch", iconType: "aws", awsIcon: "cloudwatch", x: 1150, y: 80, group: "observability",
      detail: "Log groups: /ecs/order-service, /ecs/config-service. Embedded Metric Format for custom metrics. Dashboards for p50/p99 latency. Alarms: 5xx > 1%, latency p99 > 500ms." },
    { id: "eventbridge", label: "EventBridge", iconType: "aws", awsIcon: "eventbridge", x: 1150, y: 560, group: "eventing",
      detail: "Default event bus. Rule: source=aws.ssm, detail-type=Parameter Store Change. Target: Lambda function with DLQ on SQS. Retry: 3 attempts, exponential backoff." },
    { id: "lambda", label: "AWS Lambda", iconType: "aws", awsIcon: "lambda", x: 800, y: 630, group: "eventing",
      detail: "Runtime: Java 21 (SnapStart). Triggered by EventBridge. Steps: parse changed parameter, DiscoverInstances via Cloud Map, gRPC refresh() each Config Service task. Timeout: 30s. VPC-attached." },
    { id: "cloudmap", label: "Cloud Map", iconType: "aws", awsIcon: "cloudmap", x: 520, y: 630, group: "networking",
      detail: "Namespace: config-service.local (DNS). Service: config-service, port 5000. ECS auto-registers task IPs. Used by gRPC client (DNS) and Lambda (DiscoverInstances API)." },
  ],
  flows: [
    { from: "client", to: "cognito", label: "① Authenticate", step: 1 },
    { from: "cognito", to: "client", label: "② JWT Token", step: 2 },
    { from: "client", to: "apigw", label: "③ REST + JWT", step: 3 },
    { from: "apigw", to: "cognito", label: "④ Validate", step: 4 },
    { from: "apigw", to: "vpclink", label: "⑤ Private Integration", step: 5 },
    { from: "vpclink", to: "alb", label: "⑥ REST → Order Svc", step: 6 },
    { from: "alb", to: "rest-ctrl", label: "", step: 0 },
    { from: "rest-ctrl", to: "grpc-client", label: "", step: 0 },
    { from: "grpc-client", to: "cloudmap", label: "⑦ DNS Lookup", step: 7, style: "dashed" },
    { from: "grpc-client", to: "grpc-ctrl", label: "⑧ gRPC Call", step: 8 },
    { from: "grpc-ctrl", to: "strategy-factory", label: "⑨ Route", step: 9 },
    { from: "strategy-factory", to: "dynamo-strategy", label: "tenant_config_*", step: 0 },
    { from: "strategy-factory", to: "ssm-strategy", label: "param_config_*", step: 0 },
    { from: "dynamo-strategy", to: "ep-dynamo", label: "", step: 0 },
    { from: "ep-dynamo", to: "dynamodb", label: "", step: 0 },
    { from: "dynamodb", to: "kms", label: "Encrypt", step: 0 },
    { from: "ssm-strategy", to: "ep-ssm", label: "", step: 0 },
    { from: "ep-ssm", to: "param-store", label: "", step: 0 },
    { from: "param-store", to: "kms", label: "Encrypt", step: 0 },
    { from: "param-store", to: "eventbridge", label: "⑩ Change Event", step: 10 },
    { from: "eventbridge", to: "lambda", label: "⑪ Trigger", step: 11 },
    { from: "lambda", to: "cloudmap", label: "⑫ DNS Lookup", step: 12 },
    { from: "lambda", to: "grpc-ctrl", label: "⑬ gRPC refresh()", step: 13, style: "dashed" },
    { from: "alb", to: "ep-cw", label: "Logs & Metrics", step: 0, style: "dashed" },
    { from: "ep-cw", to: "cloudwatch", label: "", step: 0 },
    { from: "apigw", to: "waf", label: "", step: 0 },
  ],
};
